ARG BASE_COMMIT
FROM clb_build_${BASE_COMMIT}
ARG TARGET_COMMIT
# Intentionally echo here, before `git fetch` as a form of cache busting.
RUN echo "Fetching to obtain commit: ${TARGET_COMMIT}"
RUN git fetch origin
RUN git checkout ${TARGET_COMMIT}
RUN rm -rvf /src/rpmbuild 
RUN make -j$(($(nproc) - 1)) binrpm-pkg
