FROM quay.io/fedora/fedora-bootc:latest

# Workaround...
# When installing a kernel RPM, "05-rpmostree.install" runs before depmod,
# then fails because modules.dep hasn't been created yet.
# Simply link the depmod step so it runs first. It will run again after
# the rpmostree step - but that is harmless.
RUN ln -s \
  /usr/lib/kernel/install.d/50-depmod.install \
  /usr/lib/kernel/install.d/01-depmod.install

# bcvk complains if there are multiple kernels, so remove the standard one.
RUN dnf remove -y \
  kernel \
  kernel-core \
  kernel-modules \
  kernel-modules-core

# Some niceties.
RUN dnf install -y \
  fish \
  micro \
  tmux \
  screen

