FROM quay.io/fedora/fedora-bootc:latest

# Workaround...
# "05-rpmostree.install" runs before depmod, then fails because
# modules.dep hasn't been created.
RUN ln -s \
  /usr/lib/kernel/install.d/50-depmod.install \
  /usr/lib/kernel/install.d/01-depmod.install

# bcvk complains if there are multiple kernels, so remove the standard one.
RUN dnf remove -y \
  kernel \
  kernel-core \
  kernel-modules \
  kernel-modules-core

RUN dnf install -y \
  micro \
  tmux \
  screen

#COPY root_authorized_keys /usr/lib/ssh/root_authorized_keys
#RUN mkdir -p /usr/lib/tmpfiles.d
#RUN cat > /usr/lib/tmpfiles.d/root-ssh.conf <<'EOF'
#d /var/roothome/.ssh 0700 root root -
#C /var/roothome/.ssh/authorized_keys 0600 root root - /usr/lib/ssh/root_authorized_keys
#EOF

#RUN echo "PermitRootLogin prohibit-password" > /etc/ssh/sshd_config.d/90-allow-root.conf
